apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: api
build:
  artifacts:
    - image: kubectl-argo-rollouts
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  helm:
    releases:
      - name: app
        chartPath: ./app
        setValueTemplates:
          image: "{{ .IMAGE_FULLY_QUALIFIED_kubectl_argo_rollouts }}"
