apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    name: "{{ .Chart.Name }}-sa"
  name: "{{ .Chart.Name }}-sa"
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: "{{ .Chart.Name }}-role"
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Chart.Name }}-binding"
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-sa"
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: "{{ .Chart.Name }}-role"
  apiGroup: rbac.authorization.k8s.io
